3g3q:
  name: 3 Guys 3 Questions
  lang: EN
  explicit: clean
  collection: 3g3q
  hosts: Aaron Goodwin, Andrew Savage, and Adam Anderson
  description: Three guys ponder the finer things in life by asking each other weird questions. Each week they compete to seem the most normal while answering questions about fears, pet-peeves, and idiosyncrasies.
  artwork: "/uploads/artwork-3g3q.jpg"
  color: "#6B4AD3"
  show-twitter: "@_3g3q"
  hosts-twitter: "@aaronlmgoodwin, @a_sav, and @thatadamkid"
  email: 3guys3questions@gmail.com
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
dailyish:
  name: Daily(ish)
  collection: dailyish
  hosts: Chris Enns
  description: Just as it says on the tin this is a daily(ish) podcast from Chris Enns.
  artwork: "/uploads/artwork-dailyish.jpg"
  color: "#757474"
  keywords: tech, technology, personal, journal, family, life
  show-twitter: _dailyish
  host-twitter: ichris
  email: chris@goodstuff.fm
  supportlink: http://www.patreon.com/ichris
  RSS: http://feeds.goodstuff.fm/dailyish
  itunes: https://itunes.apple.com/ca/podcast/pdcst/id815675012
  pocketcast: http://pca.st/Vifv
  overcast: https://overcast.fm/itunes815675012/daily-ish
morningshow:
  name: Morning Show
  collection: morningshow
  hosts: Kyle Roderick and Kenny Roderick
  description: Morning Show with brothers Kyle and Kenny is a fun, comedic show that covers the top stories from the day, interesting facts, and food holidays.
  artwork: "/uploads/artwork-morningshow.jpg"
  color: #F6BE48
  keywords: tech, technology, personal, journal, family, life
  show-twitter: "@morningshowam"
  hosts-twitter: "@dogburps and @pizzarobotics"
  email: kyle@goodstuff.fm
  support: http://www.patreon.com/morningshow
  rss: http://feeds.goodstuff.fm/dailyish
  itunes: https://itunes.apple.com/ca/podcast/pdcst/id815675012
  pocketcast: http://pca.st/Vifv
  overcast: https://overcast.fm/itunes815675012/daily-ish
grownups:
  name: I Guess We're Grown-Ups Now
  collection: grownups
  hosts: Kari Halsted and Brook Shelley
  description: Morning Show with brothers Kyle and Kenny is a fun, comedic show that covers the top stories from the day, interesting facts, and food holidays.
  artwork: "/uploads/artwork-grownups.jpg"
  color: #F6BE48
  keywords: tech, technology, personal, journal, family, life
  show-twitter: "@morningshowam"
  hosts-twitter: "@dogburps and @pizzarobotics"
  email: kyle@goodstuff.fm
  support: http://www.patreon.com/morningshow
  rss: http://feeds.goodstuff.fm/dailyish
  itunes: https://itunes.apple.com/ca/podcast/pdcst/id815675012
  pocketcast: http://pca.st/Vifv
  overcast: https://overcast.fm/itunes815675012/daily-ish
nbsp:
  name: Non Breaking Space Show
  collection: nbsp
  hosts: Christopher Schmitt
  description: Morning Show with brothers Kyle and Kenny is a fun, comedic show that covers the top stories from the day, interesting facts, and food holidays.
  artwork: "/uploads/artwork-nbsp.jpg"
  color: #F6BE48
  keywords: tech, technology, personal, journal, family, life
  show-twitter: "@morningshowam"
  hosts-twitter: "@dogburps and @pizzarobotics"
  email: kyle@goodstuff.fm
  support: http://www.patreon.com/morningshow
  rss: http://feeds.goodstuff.fm/dailyish
  itunes: https://itunes.apple.com/ca/podcast/pdcst/id815675012
  pocketcast: http://pca.st/Vifv
  overcast: https://overcast.fm/itunes815675012/daily-ish
master:
  name: Goodstuff Master Feed
  lang: EN
  explicit: clean
  hosts: Goodstuff Broadcasting
  description: All episodes of all shows on Goodstuff
  artwork: "/uploads/artwork-master.jpg"
  color: "#D8574B"
  show-twitter: "@GoodstuffFM"
  hosts-twitter: ""
  email: contact@goodstuff.fm
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
atu2:
  name: The atU2 Podcast
  lang: EN
  explicit: clean
  collection: atu2
  hosts: Chris Enns and Matt McGee
  description: "Talking all things U2 including new album news, tour dates, commentary, and community discussions from the staff of @U2."
  artwork: "/uploads/artwork-atu2.jpg"
  color: "#6B4AD3"
  show-twitter: "@_3g3q"
  hosts-twitter: "@ichris and @"
  email: chris@goodstuff.fm
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
aux:
  name: Auxiliary
  lang: EN
  explicit: explicit
  collection: aux
  hosts: Goodstuff Hosts
  description: After a show is done recording, we sometimes forget to stop recording and this is what results.
  artwork: "/uploads/artwork-aux.jpg"
  color: "#6B4AD3"
  show-twitter:
  hosts-twitter:
  email: contact@goodstuff.fm
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
ll:
  name: Lost & Lemon
  lang: EN
  explicit: clean
  collection: ll
  hosts: Chris Enns, Chris Huebert
  description: A weekly talk show about starting businesses on opposite sides of the world, but on the same internet.
  artwork: "/uploads/artwork-ll.jpg"
  color: "#6B4AD3"
  show-twitter: "@GoodstuffFM"
  hosts-twitter: "@ichris and @byronboy1"
  email: 3guys3questions@gmail.com
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
neverdigdown:
  name: Never Dig Down
  lang: EN
  explicit: clean
  collection: neverdigdown
  hosts: Chris Enns, Tim Murtaugh
  description: Chris and Tim are your buddies on a journey into the world of Minecraft. Answering your questions about the game and introducing you to new and interesting ways to play Minecraft through mods.
  artwork: "/uploads/artwork-neverdigdown.jpg"
  color: "#6B4AD3"
  show-twitter: "@_3g3q"
  hosts-twitter: "@aaronlmgoodwin, @a_sav, and @thatadamkid"
  email: 3guys3questions@gmail.com
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
smym:
  name: Show Me Your Mic
  lang: EN
  explicit: clean
  collection: smym
  hosts: Chris Enns
  description: Three guys ponder the finer things in life by asking each other weird questions. Each week they compete to seem the most normal while answering questions about fears, pet-peeves, and idiosyncrasies.
  artwork: "/uploads/artwork-smym.jpg"
  color: "#6B4AD3"
  show-twitter: "@_smym"
  hosts-twitter: "@ichris"
  email: chris@goodstuff.fm
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
specials:
  name: Goodstuff Specials
  lang: EN
  explicit: explicit
  collection: specials
  hosts: Goodstuff Hosts
  description: Three guys ponder the finer things in life by asking each other weird questions. Each week they compete to seem the most normal while answering questions about fears, pet-peeves, and idiosyncrasies.
  artwork: "/uploads/artwork-specials.jpg"
  color: "#6B4AD3"
  show-twitter: "@GoodstuffFM"
  hosts-twitter:
  email: contact@goodstuff.fm
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
tirp:
  name: The Intellectual Radio Program
  lang: EN
  explicit: clean
  collection: tirp
  hosts: Aaron Goodwin, Andrew Savage, and Adam Anderson
  description: Three guys ponder the finer things in life by asking each other weird questions. Each week they compete to seem the most normal while answering questions about fears, pet-peeves, and idiosyncrasies.
  artwork: "/uploads/artwork-tirp.jpg"
  color: "#6B4AD3"
  show-twitter: "@_3g3q"
  hosts-twitter: "@aaronlmgoodwin, @a_sav, and @thatadamkid"
  email: 3guys3questions@gmail.com
  keywords: comedy, 3 guys, three guys, 3g3q, wolverine room, buddy box, juggalo, lightning round
  category1: "Arts"
  category2: "Comedy"
  category3: "Technology"
  category4:
  category5:
  rss: http://feed.3g3q.co/
  itunes: https://itunes.apple.com/us/podcast/3-guys-3-questions/id914129482
  pocketcast: http://feed.3g3q.co/
  overcast: http://feed.3g3q.co/
