backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

collections:
  - name: "todaysspecial" # Used in routes, e.g. /admin/collections/blog
    label: "Today's Special" # Used in the UI
    folder: "_todaysspecial" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{episode}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "episode"}
      - {label: "Show", name: "show", widget: "hidden", default: "todaysspecial"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Episode Number", name: "episode", widget: "number"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Audio File", name: "mp3", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
